spring:
  application:
    name: gateway
  profiles:
    active: dev

server:
  port: 10020

zuul:
  routes:
    nacos-config:
      path: /config/**
      service-id: nacos-config
      strip-prefix: true
  canary-release:
    enabled: true
#    check-type: name
